name: asp-net-ci

on:
  push:
    branches:
      - develop

jobs:

  # run build
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: get sources
        uses: actions/checkout@master
        
      - uses: actions/upload-artifact@v2
        with:
          name: sources
          path: source

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: build
        run: dotnet build source
