name: asp-net-ci

on:
  push:
    branches:
      - develop

jobs:

  # run build
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: get sources
        uses: actions/checkout@master
        
      - uses: actions/upload-artifact@v2
        with:
          name: sources
          path: Restaurant

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: make build script runnable
        run:
# make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
      - name: execute build script
        run:
# run script
        "${GITHUB_WORKSPACE}/build.sh"
    # or
    #"${{ format('{0}/.github/script.sh', github.workspace) }}"

# run tests
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/download-artifact@v2
        with:
          name: sources
      - run: dotnet build
      - name: run tests for Api
        run: dotnet test "Restaurant.RestApi.Tests/Restaurant.RestApi.Tests.csproj" --no-build --no-restore
